version: "3.8"

services:
  app:
    build: .
    container_name: app
    command: sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    labels:
      - "traefik.enable=true"
      - "traefik.subdomain=contact-level"
      - "traefik.http.services.contact-level.loadbalancer.server.port=80"
      - "traefik.http.routers.contact-level.tls.certresolver=letsEncrypt"
    volumes:
      - ./app/:/code/app
    # ports:
    #   - 8000:80
    env_file:
      - ./.prod.env

  contact_level_db:
    image: postgres
    container_name: contact_level_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: contact_level
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  worker:
    build: .
    container_name: worker
    command: celery -A app.worker worker --loglevel=INFO -Q settings
    env_file:
      - ./.prod.env
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.10.5"

networks:
  default:
    external:
      name: traefik
